openapi: 3.0.1
info:
  title: L3vpnProfile_1.0.0-tsi.240103.1150+simulator.1
  version: 1.0.0

paths:

########################################################################################################################
#   Generic Paths
########################################################################################################################
  /core-model-1-4:network-control-domain=cache/control-construct={mountName}/profile-collection/profile={uuid}/l-3vpn-profile-1-0:l-3vpn-profile-pac/l-3vpn-profile-capability:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
      - $ref: '#/components/parameters/uuid'
      - $ref: '#/components/parameters/fields'
    get:
      operationId: getCachedL3vpnProfileCapability
      summary: 'Provides L3vpnProfileCapability from cache'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      responses:
        '200':
          description: 'L3vpnProfileCapability provided from cache'
          content:
            application/json:
              schema:
                type: object
                required:
                  - l-3vpn-profile-1-0:l-3vpn-profile-capability
                properties:
                  l-3vpn-profile-1-0:l-3vpn-profile-capability:
                    $ref: '#/components/schemas/l-3vpn-profile-capability'
                example:
                  l-3vpn-profile-1-0:l-3vpn-profile-capability:
                    profile-naming-is-avail: true
                    l-3vpn-based-on-ip-v-6-is-avail: true
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
        '4XX':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '500':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        default:
          $ref: '#/components/responses/responseForErroredServiceRequests'
  /core-model-1-4:network-control-domain=cache/control-construct={mountName}/profile-collection/profile={uuid}/l-3vpn-profile-1-0:l-3vpn-profile-pac/l-3vpn-profile-configuration:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
      - $ref: '#/components/parameters/uuid'
      - $ref: '#/components/parameters/fields'
    get:
      operationId: getCachedL3vpnProfileConfiguration
      summary: 'Provides L3vpnProfileConfiguration from cache'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      responses:
        '200':
          description: 'L3vpnProfileConfiguration provided from cache'
          content:
            application/json:
              schema:
                type: object
                required:
                  - l-3vpn-profile-1-0:l-3vpn-profile-configuration
                properties:
                  l-3vpn-profile-1-0:l-3vpn-profile-configuration:
                    $ref: '#/components/schemas/l-3vpn-profile-configuration'
                example:
                  l-3vpn-profile-1-0:l-3vpn-profile-configuration:
                    external-label: 'External label not yet defined.'
                    l-3vpn-description: 'VPN description not yet defined.'
                    l-3vpn-configuration-list:
                      - label-mode: 'l-3vpn-profile-1-0:LABEL_MODE_TYPE_PER_INSTANCE'
                        route-distinguisher:
                          vpn-number: 0
                          device-identifier-kind: 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_LOOP_BACK_IP_ADDRESS'
                          loop-back-ip-address: '168.252.005.43'
                          as-number: 0
                        route-target-import-list:
                          - vpn-number: 0
                            device-identifier-kind: 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_LOOP_BACK_IP_ADDRESS'
                            loop-back-ip-address: '252.057.254.254'
                            as-number: 0
                        route-target-export-list:
                          - vpn-number: 0
                            device-identifier-kind: 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_LOOP_BACK_IP_ADDRESS'
                            loop-back-ip-address: '212.219.225.254'
                            as-number: 0
                        address-family: 'l-3vpn-profile-1-0:ADDRESS_FAMILY_TYPE_IPV4-FAMILY'
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
        '4XX':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '500':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        default:
          $ref: '#/components/responses/responseForErroredServiceRequests'

  /core-model-1-4:network-control-domain=live/control-construct={mountName}/l-3vpn-profile-1-0:create-l-3vpn-profile:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
    post:
      operationId: postCreateL3vpnProfile
      summary: 'Creates new instance of L3vpnProfile'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - input
              properties:
                input:
                  type: object
                  required:
                    - l-3vpn-configuration-list
                  properties:
                    external-label:
                      type: string
                    l-3vpn-description:
                      type: string
                    l-3vpn-configuration-list:
                      type: array
                      minItems: 1
                      maxItems: 2
                      x-key: label-mode
                      items:
                        type: object
                        required:
                          - label-mode
                          - route-distinguisher
                          - route-target-import-list
                          - route-target-export-list
                          - address-family
                        properties:
                          label-mode:
                            type: string
                            enum:
                              - 'l-3vpn-profile-1-0:LABEL_MODE_TYPE_PER_INSTANCE'
                              - 'l-3vpn-profile-1-0:LABEL_MODE_TYPE_PER_ROUTE'
                          route-distinguisher:
                            type: object
                            required:
                              - vpn-number
                              - device-identifier-kind
                              - loop-back-ip-address
                              - as-number
                            properties:
                              vpn-number:
                                type: integer
                                format: uint32
                              device-identifier-kind:
                                type: string
                                enum:
                                  - 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_LOOP_BACK_IP_ADDRESS'
                                  - 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_AS_NUMBER'
                                  - 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_NOT_YET_DEFINED'
                              loop-back-ip-address:
                                type: string
                                pattern: '^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
                              as-number:
                                type: integer
                                format: uint32
                          route-target-import-list:
                            type: array
                            minItems: 1
                            x-key: vpn-number
                            items:
                              type: object
                              required:
                                - vpn-number
                                - device-identifier-kind
                                - loop-back-ip-address
                                - as-number
                              properties:
                                vpn-number:
                                  type: integer
                                  format: uint32
                                device-identifier-kind:
                                  type: string
                                  enum:
                                    - 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_LOOP_BACK_IP_ADDRESS'
                                    - 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_AS_NUMBER'
                                    - 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_NOT_YET_DEFINED'
                                loop-back-ip-address:
                                  type: string
                                  pattern: '^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
                                as-number:
                                  type: integer
                                  format: uint32
                          route-target-export-list:
                            type: array
                            minItems: 1
                            x-key: vpn-number
                            items:
                              type: object
                              required:
                                - vpn-number
                                - device-identifier-kind
                                - loop-back-ip-address
                                - as-number
                              properties:
                                vpn-number:
                                  type: integer
                                  format: uint32
                                device-identifier-kind:
                                  type: string
                                  enum:
                                    - 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_LOOP_BACK_IP_ADDRESS'
                                    - 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_AS_NUMBER'
                                    - 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_NOT_YET_DEFINED'
                                loop-back-ip-address:
                                  type: string
                                  pattern: '^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
                                as-number:
                                  type: integer
                                  format: uint32
                          address-family:
                            type: string
                            enum:
                              - 'l-3vpn-profile-1-0:ADDRESS_FAMILY_TYPE_IPV4-FAMILY'
                              - 'l-3vpn-profile-1-0:ADDRESS_FAMILY_TYPE_IPV6-FAMILY'
                              - 'l-3vpn-profile-1-0:ADDRESS_FAMILY_TYPE_UNKNOWN'
                              - 'l-3vpn-profile-1-0:ADDRESS_FAMILY_TYPE_NOT_YET_DEFINED'
              example:
                input:
                  external-label: 'string'
                  l-3vpn-description: 'string'
                  l-3vpn-configuration-list:
                    - label-mode: 'l-3vpn-profile-1-0:LABEL_MODE_TYPE_PER_INSTANCE'
                      route-distinguisher:
                        vpn-number: 0
                        device-identifier-kind: 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_LOOP_BACK_IP_ADDRESS'
                        loop-back-ip-address: '201.246.243.251'
                        as-number: 0
                      route-target-import-list:
                        - vpn-number: 0
                          device-identifier-kind: 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_LOOP_BACK_IP_ADDRESS'
                          loop-back-ip-address: '250.211.252.255'
                          as-number: 0
                      route-target-export-list:
                        - vpn-number: 0
                          device-identifier-kind: 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_LOOP_BACK_IP_ADDRESS'
                          loop-back-ip-address: '210.57.6.137'
                          as-number: 0
                      address-family: 'l-3vpn-profile-1-0:ADDRESS_FAMILY_TYPE_IPV4-FAMILY'  
      responses:
        '200':
          description: 'New instance of L3vpnProfile created'
          content:
            application/json:
              schema:
                type: object
                required:
                  - l-3vpn-profile-1-0:output
                properties:
                  l-3vpn-profile-1-0:output:
                    type: object
                    required:
                      - created-l-3vpn-profile
                    properties:
                      created-l-3vpn-profile:
                        type: string
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
        '4XX':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '500':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        default:
          $ref: '#/components/responses/responseForErroredServiceRequests'
  /core-model-1-4:network-control-domain=live/control-construct={mountName}/l-3vpn-profile-1-0:modify-l-3vpn-profile:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
    post:
      operationId: postModifyL3vpnProfile
      summary: 'Modifies an existing L3vpnProfile'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - input
              properties:
                input:
                  type: object
                  required:
                    - l-3vpn-profile-to-be-modified
                  properties:
                    l-3vpn-profile-to-be-modified:
                      type: string
                    external-label:
                      type: string
                    l-3vpn-description:
                      type: string
                    l-3vpn-configuration-list:
                      type: array
                      minItems: 0
                      maxItems: 2
                      x-key: label-mode
                      items:
                        type: object
                        properties:
                          label-mode:
                            type: string
                            enum:
                              - 'l-3vpn-profile-1-0:LABEL_MODE_TYPE_PER_INSTANCE'
                              - 'l-3vpn-profile-1-0:LABEL_MODE_TYPE_PER_ROUTE'
                          route-distinguisher:
                            type: object
                            properties:
                              vpn-number:
                                type: integer
                                format: uint32
                              device-identifier-kind:
                                type: string
                                enum:
                                  - 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_LOOP_BACK_IP_ADDRESS'
                                  - 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_AS_NUMBER'
                                  - 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_NOT_YET_DEFINED'
                              loop-back-ip-address:
                                type: string
                                pattern: '^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
                              as-number:
                                type: integer
                                format: uint32
                          route-target-import-list:
                            type: array
                            minItems: 1
                            x-key: vpn-number
                            items:
                              type: object
                              required:
                                - vpn-number
                              properties:
                                vpn-number:
                                  type: integer
                                  format: uint32
                                device-identifier-kind:
                                  type: string
                                  enum:
                                    - 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_LOOP_BACK_IP_ADDRESS'
                                    - 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_AS_NUMBER'
                                    - 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_NOT_YET_DEFINED'
                                loop-back-ip-address:
                                  type: string
                                  pattern: '^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
                                as-number:
                                  type: integer
                                  format: uint32
                          route-target-export-list:
                            type: array
                            minItems: 1
                            x-key: vpn-number
                            items:
                              type: object
                              required:
                                - vpn-number
                              properties:
                                vpn-number:
                                  type: integer
                                  format: uint32
                                device-identifier-kind:
                                  type: string
                                  enum:
                                    - 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_LOOP_BACK_IP_ADDRESS'
                                    - 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_AS_NUMBER'
                                    - 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_NOT_YET_DEFINED'
                                loop-back-ip-address:
                                  type: string
                                  pattern: '^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
                                as-number:
                                  type: integer
                                  format: uint32
                          address-family:
                            type: string
                            enum:
                              - 'l-3vpn-profile-1-0:ADDRESS_FAMILY_TYPE_IPV4-FAMILY'
                              - 'l-3vpn-profile-1-0:ADDRESS_FAMILY_TYPE_IPV6-FAMILY'
                              - 'l-3vpn-profile-1-0:ADDRESS_FAMILY_TYPE_UNKNOWN'
                              - 'l-3vpn-profile-1-0:ADDRESS_FAMILY_TYPE_NOT_YET_DEFINED'
              example:
                input:
                  l-3vpn-profile-to-be-modified: 'string'
                  external-label: 'string'
                  l-3vpn-description: 'string'
                  l-3vpn-configuration-list:
                    - label-mode: 'l-3vpn-profile-1-0:LABEL_MODE_TYPE_PER_INSTANCE'
                      route-distinguisher:
                        vpn-number: 0
                        device-identifier-kind: 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_LOOP_BACK_IP_ADDRESS'
                        loop-back-ip-address: '06.252.253.252'
                        as-number: 0
                      route-target-import-list:
                        - vpn-number: 0
                          device-identifier-kind: 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_LOOP_BACK_IP_ADDRESS'
                          loop-back-ip-address: '244.8.251.56'
                          as-number: 0
                      route-target-export-list:
                        - vpn-number: 0
                          device-identifier-kind: 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_LOOP_BACK_IP_ADDRESS'
                          loop-back-ip-address: '251.39.255.239'
                          as-number: 0
                      address-family: 'l-3vpn-profile-1-0:ADDRESS_FAMILY_TYPE_IPV4-FAMILY'
      responses:
        '204':
          description: 'Instance of L3vpnProfile updated'
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
        '4XX':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '500':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        default:
          $ref: '#/components/responses/responseForErroredServiceRequests'
  /core-model-1-4:network-control-domain=live/control-construct={mountName}/l-3vpn-profile-1-0:delete-l-3vpn-profile:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
    post:
      operationId: postDeleteL3vpnProfile
      summary: 'Deletes an instance of L3vpnProfile'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - input
              properties:
                input:
                  type: object
                  required:
                    - obsolete-l-3vpn-profile
                  properties:
                    obsolete-l-3vpn-profile:
                      type: string
              example:
                input:
                  obsolete-l-3vpn-profile: 'string'  
      responses:
        '204':
          description: 'Instance of L3vpnProfile deleted'
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
        '4XX':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '500':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        default:
          $ref: '#/components/responses/responseForErroredServiceRequests'


########################################################################################################################
#   Common Components
########################################################################################################################
components:
  parameters:
    user:
      name: user
      in: header
      required: true
      schema:
        type: string
        example: 'User Name'
      description: 'User identifier from the system starting the service call'
    originator:
      name: originator
      in: header
      required: true
      schema:
        type: string
        minLength: 3
        example: 'Resolver'
      description: >
        'Identification for the system consuming the API, as defined in
         [/core-model-1-4:control-construct/logical-termination-point={uuid}/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-configuration/application-name]'
    x-correlator:
      name: x-correlator
      in: header
      required: true
      schema:
        type: string
        pattern: '^[0-9A-Fa-f]{8}(?:-[0-9A-Fa-f]{4}){3}-[0-9A-Fa-f]{12}$'
        description: 'Empty string accepted from external applications.'
        example: '550e8400-e29b-11d4-a716-446655440000'
      description: 'UUID for the service execution flow that allows to correlate requests and responses'
    trace-indicator:
      name: trace-indicator
      in: header
      required: true
      schema:
        type: string
        pattern: '^([0-9]+)(\.([0-9]+))*$'
        description: 'Empty string accepted from external applications.'
        example: '1.3.1'
      description: 'Sequence of request numbers along the flow'
    customer-journey:
      name: customer-journey
      in: header
      required: true
      schema:
        type: string
        example: 'Unknown value'
      description: 'Holds information supporting customer’s journey to which the execution applies'
    mountName:
      name: mountName
      in: path
      required: true
      schema:
        type: string
        example: '222250001'
      description: 'The mountName of the device that is addressed by the request'
    uuid:
      name: uuid
      in: path
      required: true
      schema:
        type: string
        example: 'LTP-MWPS-TTP-1-1'
      description: 'Instance identifier that is unique within the device'
    uuid1:
      name: uuid1
      in: path
      required: true
      schema:
        type: string
        example: 'LTP-MWPS-TTP-1-1'
      description: 'Another instance identifier that is unique within the device'
    localId:
      name: localId
      in: path
      required: true
      schema:
        type: string
        example: 'LP-MWPS-TTP-1-1'
      description: 'Instance identifier that is unique within its list'
    fields:
      name: fields
      in: query
      required: false
      schema:
        type: string
        example: 'node(node-id;netconf-node-topology:connection-status)'
      description: 'Query parameter to filter ressources according to RFC8040 fields filter spec'
  responses:
    responseForErroredServiceRequests:
      description: 'Response in case of errored service requests'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorDescription'
      headers:
        x-correlator:
          schema:
            type: string
            pattern: '^[0-9A-Fa-f]{8}(?:-[0-9A-Fa-f]{4}){3}-[0-9A-Fa-f]{12}$'
            example: '550e8400-e29b-11d4-a716-446655440000'
          description: 'UUID for the service execution flow that allows to correlate requests and responses. Its value must be identical at the response compared with its corresponding request'
        exec-time:
          schema:
            type: integer
            example: 1100
          description: 'Value written by the service provider, reporting the total elapsed time for the execution, including all the additional processing needed to retrieve the data from the backend service. Expressed in milliseconds'
        backend-time:
          schema:
            type: integer
            example: 850
          description: 'Value written by the service provider, reporting the elapsed time for data retrieval from the backend (service invocation, database access…). Expressed in milliseconds'
    responseForErroredOamRequests:
      description: 'Response in case of errored OaM requests'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorDescription'
  headers:
    x-correlator:
      schema:
        type: string
        example: '550e8400-e29b-11d4-a716-446655440000'
      description: 'UUID for the service execution flow that allows to correlate requests and responses. Its value must be identical at the response compared with its corresponding request'
    exec-time:
      schema:
        type: integer
        example: 1100
      description: 'Value written by the service provider, reporting the total elapsed time for the execution, including all the additional processing needed to retrieve the data from the backend service. Expressed in milliseconds'
    backend-time:
      schema:
        type: integer
        example: 850
      description: 'Value written by the service provider, reporting the elapsed time for data retrieval from the backend (service invocation, database access…). Expressed in milliseconds'
    life-cycle-state:
      schema:
        type: string
        enum:
          - 'EXPERIMENTAL'
          - 'OPERATIONAL'
          - 'DEPRECATED'
          - 'OBSOLETE'
          - 'UNKNOWN'
          - 'NOT_YET_DEFINED'
        example: 'EXPERIMENTAL'
  schemas:
    errorDescription:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

    l-3vpn-profile-capability:
      type: object
      required:
        - profile-naming-is-avail
        - l-3vpn-based-on-ip-v-6-is-avail
      properties:
        profile-naming-is-avail:
          type: boolean
        l-3vpn-based-on-ip-v-6-is-avail:
          type: boolean
    l-3vpn-profile-configuration:
      type: object
      required:
        - external-label
        - l-3vpn-description
        - l-3vpn-configuration-list
      properties:
        external-label:
          type: string
        l-3vpn-description:
          type: string
        l-3vpn-configuration-list:
          type: array
          minItems: 1
          maxItems: 2
          x-key: label-mode
          items:
            type: object
            required:
              - label-mode
              - route-distinguisher
              - route-target-import-list
              - route-target-export-list
              - address-family
            properties:
              label-mode:
                type: string
                enum:
                  - 'l-3vpn-profile-1-0:LABEL_MODE_TYPE_PER_INSTANCE'
                  - 'l-3vpn-profile-1-0:LABEL_MODE_TYPE_PER_ROUTE'
              route-distinguisher:
                type: object
                required:
                  - vpn-number
                  - device-identifier-kind
                  - loop-back-ip-address
                  - as-number
                properties:
                  vpn-number:
                    type: integer
                    format: uint32
                  device-identifier-kind:
                    type: string
                    enum:
                      - 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_LOOP_BACK_IP_ADDRESS'
                      - 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_AS_NUMBER'
                      - 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_NOT_YET_DEFINED'
                  loop-back-ip-address:
                    type: string
                  as-number:
                    type: integer
                    format: uint32
              route-target-import-list:
                type: array
                minItems: 1
                x-key: vpn-number
                items:
                  type: object
                  required:
                    - vpn-number
                    - device-identifier-kind
                    - loop-back-ip-address
                    - as-number
                  properties:
                    vpn-number:
                      type: integer
                      format: uint32
                    device-identifier-kind:
                      type: string
                      enum:
                        - 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_LOOP_BACK_IP_ADDRESS'
                        - 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_AS_NUMBER'
                        - 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_NOT_YET_DEFINED'
                    loop-back-ip-address:
                      type: string
                    as-number:
                      type: integer
                      format: uint32
              route-target-export-list:
                type: array
                minItems: 1
                x-key: vpn-number
                items:
                  type: object
                  required:
                    - vpn-number
                    - device-identifier-kind
                    - loop-back-ip-address
                    - as-number
                  properties:
                    vpn-number:
                      type: integer
                      format: uint32
                    device-identifier-kind:
                      type: string
                      enum:
                        - 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_LOOP_BACK_IP_ADDRESS'
                        - 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_AS_NUMBER'
                        - 'l-3vpn-profile-1-0:DEVICE_IDENTIFIER_KIND_TYPE_NOT_YET_DEFINED'
                    loop-back-ip-address:
                      type: string
                    as-number:
                      type: integer
                      format: uint32
              address-family:
                type: string
                enum:
                  - 'l-3vpn-profile-1-0:ADDRESS_FAMILY_TYPE_IPV4-FAMILY'
                  - 'l-3vpn-profile-1-0:ADDRESS_FAMILY_TYPE_IPV6-FAMILY'
                  - 'l-3vpn-profile-1-0:ADDRESS_FAMILY_TYPE_UNKNOWN'
                  - 'l-3vpn-profile-1-0:ADDRESS_FAMILY_TYPE_NOT_YET_DEFINED'

  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: operation-key
    basicAuth:
      type: http
      scheme: basic
